theme: jekyll-theme-minimal
title: Resources for My Data Science Journey
description: This page highlights the key resources I am using to strengthen my data science skills. It includes a dataset of interest for practical exploration and the book R for Data Science, which supports my learning in data manipulation, visualization, and modeling using R.
